import type { TripPage } from '@/types'

export const TRIP_DATA: Record<string, TripPage> = {
  raung: {
    slug: 'raung',
    name: 'Gunung Raung',
    location: 'Banyuwangi, Jawa Timur',
    elevation: 3344,
    difficulty: 'extreme',
    duration_days: 5,
    cover: '/hero-5.webp',
    price_from: 2850000,
    quota_total: 10,
    meeting_point: 'Basecamp Kalibaru, Banyuwangi',
    include: [
      'Guide bersertifikat BNSP',
      'Logistik pendakian & konsumsi',
      'Tenda & sleeping bag',
      'P3K & emergency rescue',
      'Sertifikat pendakian',
      'Dokumentasi foto',
    ],
    exclude: [
      'Transportasi menuju basecamp',
      'Penginapan sebelum/sesudah trip',
      'Perlengkapan pribadi',
      'Asuransi jiwa',
    ],
    requirements: [
      'Usia min. 18 tahun',
      'Surat keterangan sehat dari dokter',
      'Pengalaman pendakian min. 2 gunung 3.000+ mdpl',
      'Melampirkan KTP / identitas',
    ],
    batches: [
      {
        id: 'raung-batch-1',
        label: 'Batch Mei 2026',
        start_date: '2026-05-08',
        end_date: '2026-05-12',
        quota: 10,
        filled: 7,
        price: 2850000,
        status: 'almost_full',
        agendas: [
          {
            id: 'r1-a1',
            date: '2026-05-06',
            time: '19:00',
            type: 'briefing',
            title: 'Briefing Teknis',
            body: 'Pengecekan perlengkapan, penjelasan rute, dan perkenalan tim.',
          },
          {
            id: 'r1-a2',
            date: '2026-05-08',
            time: '05:00',
            type: 'departure',
            title: 'Pemberangkatan',
            body: 'Kumpul di Basecamp Kalibaru, registrasi & pengecekan akhir.',
          },
          {
            id: 'r1-a3',
            date: '2026-05-08',
            time: '08:00',
            type: 'departure',
            title: 'Mulai Pendakian',
            body: 'Start dari pintu masuk menuju Pos 1.',
          },
          {
            id: 'r1-a4',
            date: '2026-05-10',
            time: '03:00',
            type: 'summit',
            title: 'Summit Push — Puncak Sejati',
            body: 'Pendakian malam menuju kaldera. Target puncak sebelum matahari terbit.',
          },
          {
            id: 'r1-a5',
            date: '2026-05-11',
            type: 'descent',
            title: 'Turun ke Basecamp',
            body: 'Perjalanan turun & istirahat.',
          },
          {
            id: 'r1-a6',
            date: '2026-05-12',
            time: '12:00',
            type: 'finish',
            title: 'Selesai & Selamat Jalan',
            body: 'Pembagian sertifikat, foto bersama, dan pelepasan.',
          },
        ],
      },
      {
        id: 'raung-batch-2',
        label: 'Batch Juli 2026',
        start_date: '2026-07-10',
        end_date: '2026-07-14',
        quota: 10,
        filled: 2,
        price: 2850000,
        status: 'open',
        agendas: [
          {
            id: 'r2-a1',
            date: '2026-07-08',
            time: '19:00',
            type: 'briefing',
            title: 'Briefing Teknis',
            body: 'Pengecekan perlengkapan & penjelasan rute.',
          },
          {
            id: 'r2-a2',
            date: '2026-07-10',
            time: '05:00',
            type: 'departure',
            title: 'Pemberangkatan',
            body: 'Kumpul di Basecamp Kalibaru.',
          },
          {
            id: 'r2-a3',
            date: '2026-07-12',
            time: '03:00',
            type: 'summit',
            title: 'Summit Push — Puncak Sejati',
            body: 'Pendakian malam menuju kaldera.',
          },
          {
            id: 'r2-a4',
            date: '2026-07-14',
            time: '12:00',
            type: 'finish',
            title: 'Selesai & Selamat Jalan',
          },
        ],
      },
    ],
  },

  argopuro: {
    slug: 'argopuro',
    name: 'Gunung Argopuro',
    location: 'Probolinggo–Situbondo, Jawa Timur',
    elevation: 3088,
    difficulty: 'hard',
    duration_days: 7,
    cover: '/hero-2.webp',
    price_from: 1950000,
    quota_total: 12,
    meeting_point: 'Basecamp Baderan, Situbondo',
    include: [
      'Guide lokal berpengalaman',
      'Logistik & konsumsi selama pendakian',
      'Tenda & sleeping bag',
      'P3K & emergency rescue',
      'Sertifikat pendakian',
    ],
    exclude: [
      'Transportasi menuju basecamp',
      'Penginapan sebelum/sesudah trip',
      'Perlengkapan pribadi',
      'Asuransi jiwa',
    ],
    requirements: [
      'Usia min. 17 tahun',
      'Kondisi fisik prima (tidak ada riwayat jantung/asma berat)',
      'Pengalaman pendakian minimal (pemula dengan pelatihan fisik OK)',
      'Melampirkan KTP / identitas',
    ],
    batches: [
      {
        id: 'argo-batch-1',
        label: 'Batch Juni 2026',
        start_date: '2026-06-05',
        end_date: '2026-06-11',
        quota: 12,
        filled: 12,
        price: 1950000,
        status: 'full',
        agendas: [
          {
            id: 'a1-a1',
            date: '2026-06-04',
            time: '20:00',
            type: 'briefing',
            title: 'Briefing & Pengecekan',
            body: 'Perkenalan tim & cek perlengkapan wajib.',
          },
          {
            id: 'a1-a2',
            date: '2026-06-05',
            time: '06:00',
            type: 'departure',
            title: 'Mulai Pendakian dari Baderan',
          },
          {
            id: 'a1-a3',
            date: '2026-06-08',
            time: '05:30',
            type: 'summit',
            title: 'Summit — Puncak Rengganis',
            body: 'Menuju puncak Rengganis lewat padang edelweis.',
          },
          {
            id: 'a1-a4',
            date: '2026-06-11',
            time: '14:00',
            type: 'finish',
            title: 'Finish di Bremi',
            body: 'Turun via jalur Bremi, Probolinggo.',
          },
        ],
      },
      {
        id: 'argo-batch-2',
        label: 'Batch Agustus 2026',
        start_date: '2026-08-07',
        end_date: '2026-08-13',
        quota: 12,
        filled: 4,
        price: 1950000,
        status: 'open',
        agendas: [
          {
            id: 'a2-a1',
            date: '2026-08-06',
            time: '20:00',
            type: 'briefing',
            title: 'Briefing & Pengecekan',
          },
          {
            id: 'a2-a2',
            date: '2026-08-07',
            time: '06:00',
            type: 'departure',
            title: 'Mulai Pendakian dari Baderan',
          },
          {
            id: 'a2-a3',
            date: '2026-08-10',
            time: '05:30',
            type: 'summit',
            title: 'Summit — Puncak Rengganis',
          },
          {
            id: 'a2-a4',
            date: '2026-08-13',
            time: '14:00',
            type: 'finish',
            title: 'Finish di Bremi',
          },
        ],
      },
    ],
  },
}

export function getTripBySlug(slug: string): TripPage | null {
  return TRIP_DATA[slug] ?? null
}

export function getAllTrips(): TripPage[] {
  return Object.values(TRIP_DATA)
}
